### ISSUE TITLE
ERROR during authentication * BYE Connection is closed. 13

### ISSUE THREAD

**Issue by heguangyu5** [DanijelkMSFT/ThisandThat#2]
I follow the documentation https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth See also link **IMAP OAuth testing using powershell script** to here.

`./Get-IMAPAccessToken.ps1 -tenantID "" -clientId "" -clientsecret '' -targetMailbox "" -Verbose`

always report **ERROR during authentication * BYE Connection is closed. 13** when executing command `A01 AUTHENTICATE ...` 

even if the command is correct.

PowerShell 7.2.5 on Ubuntu 18.04

Simple copy and paste the the `A01 AUTHENTICATE ...` command  to `telnet`, **A01 OK AUTHENTICATE completed.**

This wasted my whole day!

**Comment by mro-agallegos** [comment]
I have the same issue, Did you have good luck?

**Comment by heguangyu5** [comment]
@mro-agallegos 

The documentation is ok, follow the steps I have changed my program using IMAP XOAUTH2.

By the way, `Get-IMAPAccessToken.ps1 .... -Verbose` generated IMAP `A01 AUTHENTICATE ...` command is correct, you can copy paste to `telnet -z ssl outlook.office365.com 993` to test your Azure AD application configuration.

**Comment by atc0005** [comment]
On Windows, the current version of the script works as-is for me when using client credentials auth flow.

On Ubuntu (and presumably similar distros) I encountered "hanging" commands.

The fix was to explicitly emit CRLF EOL like so:

```diff
diff --git a/Get-IMAPAccessToken.ps1 b/Get-IMAPAccessToken.ps1
index 676f924..5d06fc1 100644
--- a/Get-IMAPAccessToken.ps1
+++ b/Get-IMAPAccessToken.ps1
@@ -178,6 +178,7 @@ $Port = '993'
     $SSLstreamReader = new-object System.IO.StreamReader($sslStream)
     $SSLstreamWriter = new-object System.IO.StreamWriter($sslStream)
     $SSLstreamWriter.AutoFlush = $true
+    $SSLstreamWriter.Newline = "`r`n"
     $SSLstreamReader.ReadLine()

     Write-Host "Authenticate using XOAuth2." -ForegroundColor DarkGreen
```

This allowed the script to execute properly on Windows and Ubuntu distros with the `MSAL.PS` module installed. Tested using PowerShell v7.3.0.

References:

- https://stackoverflow.com/a/26802133/903870
- https://datatracker.ietf.org/doc/html/rfc9051

Specifically:

>    All interactions transmitted by client and server are in the form of
>    lines, that is, strings that end with a CRLF.
